# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &users:
    - &aitvaras age1fkllez8yn8tnqyrkstysdu3sg8dumzxe3jt2mkz9ls8sm8c0ddjsd2rvaq
  - &hosts:
    - &evilbook age1c5j9wyzcvccujph6plnk6jr0kr3ynca7f957vr0dx4c6gqwyw9ys9lqntx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *aitvaras
      - *evilbook
