[backdrop]
enabled = true

[bar.default]
background_opacity = 0.64999998547136784
capsule = true
center = [ "clock", "notifications" ]
end = [ "tray", "keyboard_layout", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_edge = 5
margin_ends = 5
start = [ "wallpaper", "workspaces" ]

[battery]
warning_threshold = 20

[calendar]
enabled = true

[desktop_widgets]
enabled = false

[dock]
active_monitor_only = true
auto_hide = true
enabled = true
launcher_position = "end"
monitors = [ "eDP-1" ]
pinned = [ "firefox", "com.mitchellh.ghostty", "dev.zed.Zed" ]
reserve_space = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Skellefteå, Sweden"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 720.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 768.0
    cy = 432.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.65000000000000002
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 320.0
    cx = 768.0
    cy = 224.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = false
        clock_style = "digital"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 192.0
    box_width = 400.0
    cx = 1280.0
    cy = 512.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

[shell]
niri_overview_type_to_launch_enabled = true
polkit_agent = true

    [shell.panel]
    transparency_mode = "glass"

[theme]
builtin = "Gruvbox"
community_palette = "Oxocarbon"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper.default]
path = "/home/aitvaras/Pictures/Wallpapers/wallpaperflare.com_wallpaper(4).jpg"

[wallpaper.last]
path = "/home/aitvaras/Pictures/Wallpapers/wallpaperflare.com_wallpaper(4).jpg"

[wallpaper.monitors.eDP-1]
path = "/home/aitvaras/Pictures/Wallpapers/wallpaperflare.com_wallpaper(4).jpg"

[widget.network]
show_label = false

[widget.volume]
show_label = false
