name: build-evilbook-and-puth-to-flakehub
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 3 * * *" # runs dayly 03:00

jobs:
  build-host:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v3
      - run: nix build --extra-experimental-features 'pipe-operators flakes nix-commanads' .#nixosConfigurations.evilbook.config.system.build.toplevel
      - name: Push private flake to flakehub
        uses: determinatesystems/flakehub-push@main
        with:
          rolling: true
          visibility: "private"
          include-output-paths: true
