name: build-hosts-and-push-to-flakehub
on:
  workflow_dispatch: # allows manual triggering

jobs:
  build-host:
    # timeout-minutes: 60
    runs-on: self-hosted
    strategy:
      matrix:
        host: [evilbook, evilcloud, rynepc]
      fail-fast: true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/flakehub-cache-action@v3
        with:
          use-gha-cache: "disable"
      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
  push-to-flakehub:
    runs-on: self-hosted
    needs: build-host
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Push private flake to flakehub
        uses: determinatesystems/flakehub-push@main
        with:
          rolling: true
          visibility: "private"
          include-output-paths: true
