name: build-hosts-and-push-to-flakehub
on:
  workflow_dispatch: # allows manual triggering

jobs:
  build-host:
    timeout-minutes: 15
    runs-on: blacksmith-2vcpu-ubuntu-2404
    strategy:
      matrix:
        host: [evilbook, rynepc]
      fail-fast: true
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.NIXOS_SECRETS_SSH_KEY }}
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators flakes nix-commanads
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flakehub-cache-action@v3
        with:
          use-gha-cache: true
      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
  push-to-flakehub:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    needs: build-host
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.NIXOS_SECRETS_SSH_KEY }}
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators flakes nix-commanads
      - name: Push private flake to flakehub
        uses: determinatesystems/flakehub-push@main
        with:
          rolling: true
          visibility: "private"
          include-output-paths: true
